-- CLEWRVIEWDA BIREY_ID 7,8 OLAN ÞÜBEINIDÝ VE BIREY_IDSÝ NULL'DU,EKLERSEM HATA ÇIKTI O YUZDEN 7,8 DIÞINDAKÝLERI EKLEDIK
INSERT INTO LanguageCenter.dbo.[Bireyler.Ogrenciler] ( BIREY_ID,[KAYIT_TARIHI])
SELECT [BIREY_ID],[KAYIT_TARIHI]
FROM ClearView.dbo.HASTALAR
WHERE BIREY_ID NOT BETWEEN 2 AND 18
  AND BIREY_ID IN (SELECT BIREY_ID FROM LanguageCenter.dbo.Bireyler);

  SELECT * FROM [Bireyler.Ogrenciler]

  -- SÝLECEGÝM FAZLA EKLENDÝ
  DELETE FROM [Bireyler.Ogrenciler]
WHERE ID > 39;

SELECT * 
FROM [Bireyler]
WHERE DATEDIFF(YEAR, [DOGUM_TARIHI], GETDATE()) < 18
ORDER BY AD;

SELECT * FROM [dbo].[Bireyler.Ogrenciler] WHERE BIREY_ID = 40