-- ClearView DB den ADRESLER TABlosundan veri çekitim
INSERT INTO LanguageCenter.dbo.[Epostalar] ([EPOSTA],[BIREY_ID])
SELECT [EPOSTA_ADRESI],[BIREY_ID]
FROM ClearView.[dbo].[E_POSTALAR];

-- CLEWRVIEWDA BIREY_ID 7,8 OLAN ÞÜBEINIDÝ VE BIREY_IDSÝ NULL'DU,EKLERSEM HATA ÇIKTI O YUZDEN 7,8 DIÞINDAKÝLERI EKLEDIK
INSERT INTO LanguageCenter.dbo.Epostalar (EPOSTA, BIREY_ID)
SELECT EPOSTA_ADRESI, BIREY_ID
FROM ClearView.dbo.E_POSTALAR
WHERE BIREY_ID NOT IN (7, 8)
  AND BIREY_ID IN (SELECT BIREY_ID FROM LanguageCenter.dbo.Bireyler);

SELECT * FROM [Epostalar]
SELECT * FROM E_POSTALAR