CREATE TRIGGER trg_Kurslar_Insert
ON Kurslar
AFTER INSERT
AS
BEGIN
    INSERT INTO Kurslar_Yedek (ID, SEVIYE_ID, DIL_ID, SURESI, UCRETI, KONTENJAN, TUR_ID, EKLENME_TARIHI, EKLEYEN_KULLANICI, SILINDI_MI)
    SELECT 
        ID, SEVIYE_ID, DIL_ID, SURESI, UCRETI, KONTENJAN, TUR_ID, GETDATE(), SYSTEM_USER, 0
    FROM inserted;
END;

INSERT INTO Kurslar (SEVIYE_ID, DIL_ID, SURESI, UCRETI, KONTENJAN, TUR_ID)
VALUES (2, 2, '3 Ay', 9000, 30, 1);

DELETE FROM Kurslar WHERE ID = 37;
UPDATE Kurslar SET UCRETI = 10000 WHERE ID = 36;


SELECT * FROM Kurslar_yedek
