CREATE TABLE Kurslar_Yedek (
    ID INT,
    SEVIYE_ID INT,
    DIL_ID INT,
    SURESI VARCHAR(50),
    UCRETI DECIMAL(10,2),
    KONTENJAN INT,
    TUR_ID INT,
    EKLENME_TARIHI DATETIME DEFAULT GETDATE(),
    EKLEYEN_KULLANICI NVARCHAR(50),
    SILINDI_MI BIT DEFAULT 0
);
